INSERT INTO movie_data (title, year, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster, ratings, metascore, imdb_rating, imdb_votes, imdb_id, movie_type, dvd, box_office, production, website, response)
VALUES
    ('The Garfield Movie', '2024', '', '24 May 2024', '', 'Animation, Adventure, Comedy', 'Mark Dindal', 'Paul A. Kaplan, Mark Torgove, David Reynolds', 'Hannah Waddingham, Chris Pratt, Nicholas Hoult', 'Garfield is about to go on a wild outdoor adventure. After an unexpected reunion with his long-lost father - the cat Vic - Garfield and Odie are forced to abandon their pampered life to join Vic in a hilarious, high-stakes heist.', 'English', 'United Kingdom, United States', 'N/A', 'https://m.media-amazon.com/images/M/MV5BNzk4ODdiOTEtMTk3YS00MzZmLTgyOWMtYzc1NjgxYWE2MmMyXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt5779228', 'movie', '', '', '', '', ''),

    ('Untitled Karate Kid Movie', '2024', '', '13 Dec 2024', '', 'Action, Drama, Family', 'Jonathan Entwistle', 'Rob Lieber', 'Jackie Chan, Ralph Macchio', 'Plot under wraps.', 'English', 'United States', 'N/A', 'N/A', NULL, '', 'N/A', '', 'tt1674782', 'movie', '', '', '', '', ''),

    ('Eternity Road Movie', '2024', '', '01 Jan 2024', '', 'Drama', 'Shahrzad Dadgar', 'N/A', 'Jessica Lang, Komal Patel, Yasamin Rezaei', 'N/A', 'English', 'United States', 'N/A', 'https://m.media-amazon.com/images/M/MV5BZTc2ZjhkNDItMjFlZS00M2NlLWFlN2UtMjVlMzgxYWY4ZWFlXkEyXkFqcGdeQXVyNjkyMDMwNTk@._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt16749568', 'movie', '', '', '', '', ''),

    ('Not Another Church Movie', '2024', '', '01 Jan 2023', '', 'Comedy', 'James Michael Cummings, Johnny Mack', 'Johnny Mack', 'Mickey Rourke, Jamie Foxx, Vivica A. Fox', 'It follows Taylor Pherry, who is given a mission from God Himself: to tell his familys stories and inspire his community. What he doesnt know is that the Devil has plans of his own.', 'English', 'United States', 'N/A', 'https://m.media-amazon.com/images/M/MV5BN2E3NzIwNTMtZjA0ZS00MDVhLWExZjAtMjEyM2FkNjViNGIyXkEyXkFqcGdeQXVyNDc2OTEwMzU@._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt19358036', 'movie', '', '', '', '', ''),

    ('Harvey Birdman attorney at law the movie', '2024', '', '03 Jan 2024', '', 'Crime', 'Arnes Becirovic', 'Arnes Becirovic', 'Arnes Becirovic', 'N/A', 'English', 'United States', 'N/A', 'N/A', NULL, '', 'N/A', '', 'tt19512590', 'movie', '', '', '', '', ''),

    ('D Terrifying Night Movie', '2024', '', 'N/A', '', 'Horror', 'Jongeorge Stephenson', 'Jongeorge Stephenson', 'N/A', 'N/A', 'English', 'United Kingdom', 'N/A', 'https://m.media-amazon.com/images/M/MV5BNTI5ZTE4YjctYTBkNC00NWM0LTkwYmEtMjA3ZDBmMDE1MmNiXkEyXkFqcGdeQXVyMTUyMjA2NjQ1._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt19785008', 'movie', '', '', '', '', ''),

    ('Raymans Big Movie', '2024', '', '08 Mar 2024', '', 'Animation, Adventure, Comedy', 'Grace Wan', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'https://m.media-amazon.com/images/M/MV5BMGZlMzYyM2MtNDA2NS00MWI0LTk4MGYtNDdlYmYwMzQxZjU1XkEyXkFqcGdeQXVyMTU3ODk2Mjk5._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt21271216', 'movie', '', '', '', '', ''),

    ('NJPW SMP: The Movie', '2024', '', 'N/A', '', 'Animation, Action, Adventure', 'Njplayswhat', 'Njplayswhat, TRGaming_138', 'Njplayswhat, TRGaming_138, Dream50729', 'N/A', 'English', 'Malaysia', 'N/A', 'https://m.media-amazon.com/images/M/MV5BNmM1NzlmY2EtMmNkOS00N2YwLThhNDUtYTRiMzljYWMxMThmXkEyXkFqcGdeQXVyMTcxNjk0NDEy._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt29585095', 'movie', '', '', '', '', ''),

    ('Double Standards Featured Movie', '2024', '', '14 Mar 2024', '', 'Drama', 'Marquand Ragland', 'Earlina D Gilford Shine', 'Kristyn Cheatham, Bonita Johnson, Zakee Slim Kornegay', 'Double Minded Man unstable in all his ways', 'English', 'United States', 'N/A', 'https://m.media-amazon.com/images/M/MV5BZjc5YjRiM2ItN2RmZC00NGQyLTljYTEtODlkNGNhZTk1NThlXkEyXkFqcGdeQXVyNjEzNTM0MzY@._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt29871473', 'movie', '', '', '', '', ''),

    ('Ultraman Blazar the Movie: Tokyo Kaiju Showdown', '2024', '', '23 Feb 2024', '', 'Action', 'Kiyotaka Taguchi', 'Takao Nakano', 'Tomoya Warabino, Himena Tsukimiya, Konomi Naito', 'A wave of kaiju emerges from an industrial area in Tokyo, prompting Captain Gento and the Special Kaiju Reaction Detachment (SKaRD) to engage in the relentless battle. Yet despite their efforts, the endless kaiju attack continues....', 'Japanese', 'Japan', 'N/A', 'https://m.media-amazon.com/images/M/MV5BMTM5NDdhOTgtOGJiOS00YmFlLTk4NGItODgxNmU1M2M4ZWE3XkEyXkFqcGdeQXVyMTM3NDc1OTM2._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt30107378', 'movie', '', '', '', '', ''),

    ('Haikyu!! The Movie: Decisive Battle at the Garbage Dump', '2024', '', '16 Feb 2024', '', 'Animation, Comedy, Drama', 'Susumu Mitsunaka', 'Haruichi Furudate, Susumu Mitsunaka', 'Ayumu Murase, Kaito Ishikawa, Yûki Kaji', 'N/A', 'Japanese', 'Japan', 'N/A', 'N/A', NULL, '', 'N/A', '', 'tt30476486', 'movie', '', '', '', '', ''),

    ('Cheech and Chongs Last Movie', '2024', '', 'N/A', '', 'Documentary', 'David L. Bushell', 'N/A', 'Cheech Marin, Tommy Chong, Lou Adler', 'Exploring their 5-decade career performing stand-up, making records, and starring in hit films. It covers their lives, comedy partnership, and lasting influence on pop culture.', 'English', 'United States', 'N/A', 'https://m.media-amazon.com/images/M/MV5BNjBmOGVjMzktYzM1MC00OTExLTk3MTMtZjlhYzVlM2M0NGQwXkEyXkFqcGdeQXVyMTQ4NTgxNzYx._V1_SX300.jpg', NULL, '', 'N/A', '', 'tt30833959', 'movie', '', '', '', '', ''),

    ('Untitled Xavier Gens Movie', '2024', '', 'N/A', '', 'Drama, Sport', 'Xavier Gens', 'N/A', 'Bérénice Bejo, Nassim Lyes, Léa Léviant', 'Paris hosting World Triathlon Championships. Sophia, a scientist, learns from Mika, , that a large shark is swimming deep in the river. To avoid a bloodbath, they have to join forces with Adil, the river police commander.', 'French', 'France', 'N/A', 'N/A', NULL, '', 'N/A', '', 'tt27627192', 'movie', '', '', '', '', '');